# Generated by Django 3.0.4 on 2020-03-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200306_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_unit',
            field=models.CharField(choices=[('floz', 'fluid ounce'), ('oz', 'ounce'), ('g', 'gram'), ('lb', 'pound')], default=2, max_length=100),
            preserve_default=False,
        ),
    ]
